# Generated by Django 4.2 on 2023-04-28 14:33

import Books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Books.models.upload_image_book),
        ),
    ]
